version: "3"

services:
   graphdb:
      image: graphdb
      ports:
         - "7200:7200"
      volumes:
         - ./graphdb-data:/data

   trifid: 
      image: ghcr.io/zazuko/trifid
      ports:
         - "8080:8080"
      environment:
         SPARQL_ENDPOINT_URL: "http://graphdb:7200/repositories/ustelkeria"
         DATASET_BASE_URL: "http://localhost:8080/"
   bisual:
      image: bisualizazioa
      ports:
         - "3000:3000"

