la_donacion:
  project_name: 'la_donacion'
  data_source: data/ladonacion.es
  validate: ./graphSource/tests/TestJson2rdf.py
  named_graph: http://ehu.eus/
  run: ./procesSource/source/json2rdf.py
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:7200/repositories/LaDonacion/statements
  logs: ./logs/laDonacion.log
  rdf_output: ./data/ladonacion.es/graphLaDonacion.nt

gate_cloud:
  project_name: 'gate_cloud'
  data_source: data/partido_del_negocio_vasco/alonsotegi-eraikiz.txt
  validate: ./graphSource/tests/TestJson2rdf.py
  named_graph: http://ehu.eus/
  run: ./procesSource/source/gate_cloud.py
  metadata_file: ./metadata.ttl
  delete_graph: false
  triple_store: http://localhost:7200/repositories/LaDonacion
  logs: ./logs/laDonacion.log
  rdf_output: ./data/ladonacion.es/graphSpacy.nt

la_donacion_stardog:
  project_name: 'la_donacion_stardog'
  data_source: data/ladonacion.es
  validate: ./graphSource/tests/TestJson2rdf.py
  named_graph: http://ehu.eus/
  run: ./procesSource/source/json2rdf.py
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:5820/LaDonacion/update
  logs: ./logs/laDonacion.log
  rdf_output: ./data/ladonacion.es/graphLaDonacion.nt

la_donacion_virtuoso:
  project_name: 'la_donacion_virtuoso'
  data_source: data/ladonacion.es
  validate: ./graphSource/tests/TestJson2rdf.py
  named_graph: http://ehu.eus/
  run: ./procesSource/source/json2rdf.py
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:8890/LaDonacion
  logs: ./logs/laDonacion.log
  rdf_output: ./data/ladonacion.es/graphLaDonacion.nt

la_donacion_apache_jena:
  project_name: 'la_donacion_apache_jena'
  data_source: data/ladonacion.es
  validate: ./graphSource/tests/TestJson2rdf.py
  named_graph: http://ehu.eus/
  run: ./procesSource/source/json2rdf.py
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:3030/ds/update
  logs: ./logs/laDonacion.log
  rdf_output: ./data/ladonacion.es/graphLaDonacion.nt

#Testak egiteko proiektuak
test_la_donacion:
  project_name: 'test_la_donacion'
  data_source: ./data/ladonacion.es
  validate: ./graphSource/tests/TestJson2rdf.py
  named_graph: http://ehu.eus/
  run: ./procesSource/source/json2rdf.py
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:7200/repositories/LaDonacion/statements
  logs: ./logs/laDonacion.log
  rdf_output: ./data/ladonacion.es/graphLaDonacion.nt

test_data_source:
  project_name: 'test_data_source'
  data_source: /errores/
  validate: ./graphSource/tests/TestJson2rdf.py
  named_graph: http://ehu.eus/
  run: ./procesSource/source/json2rdf.py
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:7200/repositories/LaDonacion/statements
  logs: ./logs/laDonacion.log
  rdf_output: ./data/ladonacion.es/graphLaDonacion.nt

test_named_graph:
  project_name: 'test_named_graph'
  data_source: ./data/ladonacion.es
  validate: ./graphSource/tests/TestJson2rdf.py
  named_graph: uriMal
  run: ./procesSource/source/json2rdf.py
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:7200/repositories/LaDonacion/statements
  logs: ./logs/laDonacion.log
  rdf_output: ./data/ladonacion.es/graphLaDonacion.nt

test_run:
  project_name: 'test_run'
  data_source: ./data/ladonacion.es
  validate: graphSource/
  named_graph: http://ehu.eus/
  run: error
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:7200/repositories/LaDonacion/statements
  logs: ./logs/laDonacion.log
  rdf_output: ./data/ladonacion.es/graphLaDonacion.nt

test_triple_store:
  project_name: 'test_triple_store'
  data_source: ./data/ladonacion.es
  validate: ./data/ladonacion.es/tests/TestJson2rdf.py
  named_graph: http://ehu.eus/
  run: ./procesSource/source/json2rdf.py
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: tripleStoreError
  logs: ./logs/laDonacion.log
  rdf_output: ./data/ladonacion.es/graphLaDonacion.nt

test_logs:
  project_name: 'test_logs'
  data_source: ./data/ladonacion.es
  validate: ./graphSource/tests/TestJson2rdf.py
  named_graph: http://ehu.eus/
  run: ./procesSource/source/json2rdf.py
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:7200/repositories/LaDonacion/statements
  logs: noExiste.txt
  rdf_output: ./data/ladonacion.es/graphLaDonacion.nt

test_rdf_output:
  project_name: 'test_rdf_output'
  data_source: ./data/ladonacion.es
  validate: ./graphSource/tests/TestJson2rdf.py
  named_graph: http://ehu.eus/ #Erabiliko den URI oinarria
  run: ./procesSource/source/json2rdf.py #Exekutatuko den programa
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:7200/repositories/LaDonacion/statements #Repoaren URIa
  logs: ./logs/laDonacion.log #Logaren path-a
  rdf_output: grafoError.nt




