la_donacion:
  data_source: /home/jonander/PycharmProjects/TFG-KG-RelacionesClientelares/data/ladonacion.es
  validate: /home/jonander/PycharmProjects/TFG-KG-RelacionesClientelares/tests/TestJson2rdf.py
  named_graph: http://data.ehu.eus/ladonacion #Este hay que cambiarlo
  run: /home/jonander/PycharmProjects/TFG-KG-RelacionesClientelares/procesSource/json2rdf.py
  metadata_file: ./metadata.ttl
  delete_graph: true
  triple_store: http://localhost:7200/repositories/LaDonacion/statements
  logs: /home/jonander/PycharmProjects/TFG-KG-RelacionesClientelares/logs/laDonacion.log
  rdf_output: /home/jonander/PycharmProjects/TFG-KG-RelacionesClientelares/data/ladonacion.es/graphLaDonacion.nt